name: develop-ci

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ros_ci_noetic:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@0.1.2
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: turtlebot3_msgs
          target-ros1-distro: noetic
          vcs-repo-file-url: ""
